services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: elibrary-rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: printer_user
      RABBITMQ_DEFAULT_PASS: strong_pass

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - elibrary

  postgres:
    image: postgres:15
    container_name: elibrary-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: elibrary
      POSTGRES_USER: elibrary
      POSTGRES_PASSWORD: elibrary

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U elibrary" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - elibrary

  migrate:
    image: migrate/migrate
    container_name: elibrary-migrate

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations

    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://elibrary:elibrary@postgres:5432/elibrary?sslmode=disable",
        "up"
      ]

    networks:
      - elibrary

  backend:
    build: .
    container_name: elibrary-backend
    restart: unless-stopped

    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started

    environment:
      DB_URL: postgres://elibrary:elibrary@postgres:5432/elibrary?sslmode=disable
      HTTP_ADDR: :8080
      IMAGES_PATH: /app/data/images
      RABBIT_URL: amqp://printer_user:strong_pass@rabbitmq:5672/
      RABBIT_QUEUE: print_queue

    ports:
      - "8080:8080"

    expose:
      - "8080"

    volumes:
      - ./data/images:/app/data/images

    networks:
      - elibrary
      - web

  frontend:
    build: ./client
    container_name: elibrary-frontend
    restart: unless-stopped

    expose:
      - "80"

    networks:
      - web

volumes:
  pgdata:

networks:
  elibrary:
  web:
    external: true
