services:
  postgres:
    image: postgres:15
    container_name: elibrary-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: elibrary
      POSTGRES_USER: elibrary
      POSTGRES_PASSWORD: elibrary

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U elibrary" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: elibrary-migrate

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations

    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://elibrary:elibrary@postgres:5432/elibrary?sslmode=disable",
        "up"
      ]

  backend:
    build: .
    container_name: elibrary-backend
    restart: unless-stopped

    depends_on:
      migrate:
        condition: service_completed_successfully

    environment:
      DB_URL: postgres://elibrary:elibrary@postgres:5432/elibrary?sslmode=disable
      HTTP_ADDR: :8080

  frontend:
    build: ./client
    container_name: elibrary-frontend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: elibrary-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx:/etc/nginx/conf.d

    depends_on:
      - backend
      - frontend

volumes:
  pgdata: